BookStationAppOA/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookomari.com.Models;
using DomainLayerOA.Models;
using RepositoryLayerOA;
using ServiceLayerOA.Service.Interface;
using ServiceLayerOA.Service.Implementation;

namespace Bookomari.com.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _authorService;

        public AuthorController(IAuthorService authorService)
        {
            _authorService = authorService;
        }



        // GET: Author
        public IActionResult Index(string AuthorSearchString)
        {
            var authorList = new AuthorSearchViewModel();

            authorList.Authors = _authorService.GetAllAuthors();

            if (!String.IsNullOrEmpty(AuthorSearchString))
            {
                authorList.Authors = authorList.Authors.Where(b => b.AuthorName.Contains(AuthorSearchString));
            }

            authorList.AuthorSearchString = AuthorSearchString;

            return View(authorList);
        }




        // GET: Author/Details/5
        public IActionResult Details(int id)
        {
            if (id == null || _authorService.GetAllAuthors() == null)
            {
                return NotFound();
            }

            var author = _authorService.GetSingleAuthor(id);

            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }




        // GET: Author/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Author/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(AuthorEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var author = new Author();

                author.AuthorName = model.AuthorName;
                author.Address = model.Address;
                author.AuthorPhoto = model.GetImageBytes();

                _authorService.AddAuthor(author);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }




        // GET: Author/Edit/5
        public IActionResult Edit(int id)
        {
            // Find the author to edit
            Author author = _authorService.GetSingleAuthor(id);

            // If the author doesn't exist, return a 404 error
            if (author == null)
            {
                return NotFound();
            }

            string fileName = "author.jpg";

            AuthorEditViewModel viewModel;

            using (var stream = new MemoryStream(author.AuthorPhoto))
            {
                var file = new FormFile(stream, 0, stream.Length, null, fileName)
                {
                    Headers = new HeaderDictionary(),
                    ContentType = "image/jpeg" // set the content type of your image here
                };

                // now you can use the IFormFile object as needed
                // Create a new view model for the edit form
                viewModel = new AuthorEditViewModel
                {
                    AuthorId = author.AuthorId,
                    AuthorName = author.AuthorName,
                    Address = author.Address,
                    AuthorPhoto = file
                };
            }
            return View(viewModel);
        }

        // POST: Author/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AuthorEditViewModel model)
        {
            if (id != model.AuthorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var author = _authorService.GetSingleAuthor(id);

                if (author == null)
                {
                    return NotFound();
                }

                author.AuthorName = model.AuthorName;
                author.Address = model.Address;
                author.AuthorPhoto = model.GetImageBytes();

                _authorService.UpdateAuthor(author);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }




        // GET: Author/Delete/5
        public IActionResult Delete(int id)
        {
            if (id == null || _authorService.GetAllAuthors() == null)
            {
                return NotFound();
            }

            var author = _authorService.GetSingleAuthor(id);
            if (author == null)
            {
                return NotFound();
            }

            return View(author);
        }

        // POST: Author/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_authorService.GetAllAuthors() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Authors'  is null.");
            }
            var author = _authorService.GetSingleAuthor(id);
            if (author != null)
            {
                _authorService.DeleteAuthor(author.AuthorId);
            }
            
            return RedirectToAction(nameof(Index));
        }

        private bool AuthorExists(int id)
        {
          return (_authorService.GetAllAuthors()?.Any(e => e.AuthorId == id)).GetValueOrDefault();
        }
    }
}

BookStationAppOA/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookomari.com.Models;
using DomainLayerOA.Models;
using RepositoryLayerOA;
using ServiceLayerOA.Service.Interface;

namespace Bookomari.com.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _bookService;
        private readonly IAuthorService _authorService;


        public BookController(IBookService bookService, IAuthorService authorService)
        {
            _bookService = bookService;
            _authorService = authorService;
        }


        [HttpGet]
        public IActionResult Index(string BookSearchString)
        {
            var bookList = new BookSearchViewModel();

            bookList.Books = _bookService.GetAllBooks();

            if (!String.IsNullOrEmpty(BookSearchString))
            {
                bookList.Books = bookList.Books.Where(b => b.BookName.Contains(BookSearchString));
            }

            bookList.BookSearchString = BookSearchString;

            return View(bookList);
        }



        public IActionResult Details(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var book = _bookService.GetSingleBook(id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        // GET: Book/Create
        public IActionResult Create()
        {
            // retrieve all authors from the database
            var authors = _authorService.GetAllAuthors();


            // create a new instance of the BookEditViewModel
            var model = new BookEditViewModel();

            // set the Authors property to a SelectList containing all authors
            ViewBag.Authors = new SelectList(authors, "AuthorId", "AuthorName");

            return View(model);
        }


        // POST: Book/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookEditViewModel model)
        {
            var author = _authorService.GetSingleAuthor(model.AuthorId);
            //model.Author = author;

            if (ModelState.IsValid)
            {
                var book = new Book();

                book.BookName = model.BookName;
                book.Language = model.Language;
                book.BookCoverPhoto = model.GetImageBytes();
                book.Author = author;
                book.AuthorId = model.AuthorId;

                _bookService.AddBook(book);
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }


        [HttpGet]
        public IActionResult Edit(int id)
        {
            // Find the book to edit
            var book = _bookService.GetSingleBook(id);

            // If the book doesn't exist, return a 404 error
            if (book == null)
            {
                return NotFound();
            }

            string fileName = "book.jpg";

            BookEditViewModel viewModel;

            using (var stream = new MemoryStream(book.BookCoverPhoto))
            {
                var file = new FormFile(stream, 0, stream.Length, null, fileName)
                {
                    Headers = new HeaderDictionary(),
                    ContentType = "image/jpeg" // set the content type of your image here
                };

                // now you can use the IFormFile object as needed
                // Create a new view model for the edit form
                viewModel = new BookEditViewModel
                {
                    BookId = book.BookId,
                    BookName = book.BookName,
                    Language = book.Language,
                    CoverPhoto = file,
                    AuthorId = book.AuthorId
                };
            }
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, BookEditViewModel model)
        {
            if (id != model.BookId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                var book = _bookService.GetSingleBook(id);

                if (book == null)
                {
                    return NotFound();
                }

                book.BookName = model.BookName;
                book.Language = model.Language;
                book.BookCoverPhoto = model.GetImageBytes();
                /*book.AuthorId = model.AuthorId;
                book.Author = model.Author;*/

                _bookService.UpdateBook(book);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }




        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (id == null || _bookService.GetAllBooks() == null)
            {
                return NotFound();
            }

            var book = _bookService.GetSingleBook(id);

            if (book == null)
            {
                return NotFound();
            }

            return View(book);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (_bookService.GetAllBooks() == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Books' is null.");
            }
            var book = _bookService.GetSingleBook(id);
            if (book != null)
            {
                _bookService.DeleteBook(id);
            }

            return RedirectToAction(nameof(Index));
        }

    }
}

BookStationAppOA/Views/Book/Create.cshtml
@model Bookomari.com.Models.BookEditViewModel

@{
    ViewData["Title"] = "Create";
    var Authors = ViewBag.Authors;
}

<h1>Create</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BookName" class="control-label"></label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoverPhoto" class="control-label"></label>
                <input asp-for="CoverPhoto" class="form-control-file" type="file" />
                <span asp-validation-for="CoverPhoto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuthorId" class="control-label"></label>
                <select asp-for="AuthorId" class ="form-control" asp-items="Authors"></select>
                @*<input type="hidden" asp-for="AuthorId" />
                <input type="hidden" asp-for="Author.AuthorId" />
                <input type="hidden" asp-for="Author.AuthorName" />
                <input type="hidden" asp-for="Author.Address" />
                <input type="hidden" asp-for="Author.AuthorPhoto" />
                <input type="hidden" asp-for="Author.Books" />*@                
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStationAppOA/Views/Book/Delete.cshtml
@model DomainLayerOA.Models.Book

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookCoverPhoto)
        </dt>
        <dd class = "col-sm-10">
            <img src="data:image;base64,@Convert.ToBase64String(Model.BookCoverPhoto)" alt="Book cover photo" width="200" height="200" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Author.AuthorName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Author.AuthorName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BookId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookStationAppOA/Views/Book/Details.cshtml
@model DomainLayerOA.Models.Book

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BookName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Language)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Language)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BookCoverPhoto)
        </dt>
        <dd class = "col-sm-10">
            <img src="data:image;base64,@Convert.ToBase64String(Model.BookCoverPhoto)" alt="Book cover photo" width="200" height="200" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Author.AuthorName)
        </dt>
        <dd class="col-sm-10">
            <a asp-controller="Author" asp-action="Details" asp-route-id="@Model.AuthorId">@Html.DisplayFor(model => model.Author.AuthorName)</a>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

BookStationAppOA/Views/Book/Edit.cshtml
@model Bookomari.com.Models.BookEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Book</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="BookName" class="control-label"></label>
                <input asp-for="BookName" class="form-control" />
                <span asp-validation-for="BookName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Language" class="control-label"></label>
                <input asp-for="Language" class="form-control" />
                <span asp-validation-for="Language" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoverPhoto" class="control-label">Select an image</label>                             
                <input asp-for="CoverPhoto" class="form-control-file" type="file" />
                <span asp-validation-for="CoverPhoto" class="text-danger"></span>
            </div>

            <input type="hidden" asp-for="BookId" />
            <input type="hidden" asp-for="AuthorId" />
            @*<input type="hidden" asp-for="Author.AuthorId" />
            <input type="hidden" asp-for="Author.AuthorName" />
            <input type="hidden" asp-for="Author.Address" />
            <input type="hidden" asp-for="Author.AuthorPhoto" />
            <input type="hidden" asp-for="Author.Books" />*@

            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookStationAppOA/Views/Book/Index.cshtml
@model Bookomari.com.Models.BookSearchViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create" >Create New Book</a>
</p>

<form asp-action="Index" method="get">
    <div class="form-group row">
        <label asp-for="BookSearchString" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-6">
            <input type="text" asp-for="BookSearchString" class="form-control" placeholder="Search by Book Name">
            <div id="search-results"></div>
        </div>
        <div class="col-sm-4">
            <button type="submit" class="btn btn-primary">Search</button>
        </div>
    </div>
</form>

<br />
<br />

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Books.FirstOrDefault().BookName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books.FirstOrDefault().Author.AuthorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books.FirstOrDefault().BookCoverPhoto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Books) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.BookName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author.AuthorName)
            </td>
            <td>
                <img src="data:image;base64,@Convert.ToBase64String(item.BookCoverPhoto)" alt="Book cover photo" width="200" height="200" />
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BookId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BookId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BookId">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>